### PR TITLE
Add a very minimalistic autotool implementation

### PR DESCRIPTION
**Pull request by airween**
Pleas note, that `autotools` script wants to remove the `core*` files. To avoid this conflict, I renamed the `core` to `libcoraza-core`, and the `utils` to `libcoraza-utils`.

In case of Linux, I also add some new steps: build the archive files, not just the shared objects.

There are many tasks in this project, eg. decide the license (actually it's empty), make more dependencies (Go version, ...) and so on.

### CODE REVIEW

**Comment by fzipi** [comment]
Some comments while following the docs on Mac:
```
❯ sh -x build.sh
+ rm -rf autom4te.cache
+ rm -f aclocal.m4
+ case `uname` in
++ uname
+ glibtoolize --force --copy
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'macros'.
glibtoolize: copying file 'macros/libtool.m4'
glibtoolize: copying file 'macros/ltoptions.m4'
glibtoolize: copying file 'macros/ltsugar.m4'
glibtoolize: copying file 'macros/ltversion.m4'
glibtoolize: copying file 'macros/lt~obsolete.m4'
+ autoreconf --install
configure.ac:19: error: AM_INIT_AUTOMAKE expanded multiple times
/usr/local/Cellar/automake/1.16.5/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:7: the top level
/usr/local/Cellar/automake/1.16.5/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:19: the top level
autom4te: error: /usr/local/opt/m4/bin/m4 failed with exit status: 1
aclocal: error: /usr/local/Cellar/autoconf/2.71/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
+ autoheader
+ automake --foreign --copy
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:35: error: required file './config.guess' not found
configure.ac:35:   'automake --add-missing' can install 'config.guess'
configure.ac:35: error: required file './config.sub' not found
configure.ac:35:   'automake --add-missing' can install 'config.sub'
Makefile.am:6: error: LINUX does not appear in AM_CONDITIONAL
Makefile.am:11: error: OSX does not appear in AM_CONDITIONAL
tests/Makefile.am:2: error: LINUX does not appear in AM_CONDITIONAL
tests/Makefile.am:6: error: OSX does not appear in AM_CONDITIONAL
+ autoconf --force
configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:24: error: possibly undefined macro: AM_PROG_AR
configure.ac:57: error: possibly undefined macro: AM_CONDITIONAL
+ rm -rf autom4te.cache
```

**Comment by fzipi** [comment]
Looks like `build.sh` file hasn't got the executable bit set.

**Comment by airween** [comment]
> Looks like `build.sh` file hasn't got the executable bit set.

I'm afraid I can't solve that issue:

```
$ ls -la build.sh 
-rwxr-xr-x 1 airween airween 278 Feb  24 09.38 build.sh
```

But I've fixed this error:
```
/usr/local/Cellar/automake/1.16.5/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:7: the top level
/usr/local/Cellar/automake/1.16.5/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:19: the top level
autom4te: error: /usr/local/opt/m4/bin/m4 failed with exit status: 1
```
in 5ab5441.

Can you try it again?

**Comment by fzipi** [comment]
Yes, this is my new try:
```
❯ git apply 3.patch
Found existing alias for "git apply". You should use: "gap"
3.patch:571: new blank line at EOF.
+
3.patch:665: new blank line at EOF.
+
warning: 2 lines add whitespace errors.
❯ ./build.sh
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'macros'.
glibtoolize: copying file 'macros/libtool.m4'
glibtoolize: copying file 'macros/ltoptions.m4'
glibtoolize: copying file 'macros/ltsugar.m4'
glibtoolize: copying file 'macros/ltversion.m4'
glibtoolize: copying file 'macros/lt~obsolete.m4'
.configure.ac:22: installing './ar-lib'
configure.ac:20: installing './compile'
configure.ac:33: installing './config.guess'
configure.ac:33: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
/configure%
❯ ./configure
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for ar... ar
checking the archiver (ar) interface... ar
checking whether make sets $(MAKE)... (cached) yes
checking for go... true
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking build system type... x86_64-apple-darwin21.3.0
checking host system type... x86_64-apple-darwin21.3.0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/local/bin/gsed
checking for grep that handles long lines and -e... /usr/local/bin/ggrep
checking for egrep... /usr/local/bin/ggrep -E
checking for fgrep... /usr/local/bin/ggrep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786432
checking how to convert x86_64-apple-darwin21.3.0 file names to x86_64-apple-darwin21.3.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin21.3.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin21.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
----------------------------------------------------------------------

 libcoraza Version 0.1 configuration:

 OS Type	Darwin
 Prefix 	/usr/local
 Preprocessor	gcc -E
 C Compiler	gcc -g -O2
 Go Version	go1.17.6

-----------------------------------------------------------------------
❯ make
CC=gcc go build -buildmode=c-archive -o coraza_core.dylib libcoraza-core/core.go
CC=gcc go build -buildmode=c-archive -o coraza_utils.dylib libcoraza-utils/utils.go
mv libcorazacore.h coraza_core.h
mv: libcorazacore.h: No such file or directory
make: *** [build-osx] Error 1
```

**Pull request merged**
